spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  port : 8081

feign.compression.request.enabled : true
feign.compression.request.mime-types: text/xml,application/xml,application/json
feign.compression.request.min-request-size : 2048
feign:
  autoconfiguration:
    jackson:
      enabled: true