spring:
  data:
    mongodb:
      uri: mongodb://local-mongo-usr:local-mongo-pwd@localhost:27017/data-svc?authSource=admin
      database: data-svc
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  port : 8082