spring:
  data:
    mongodb:
      uri: mongodb://local-mongo-usr:local-mongo-pwd@localhost:27017/test-svc?authSource=admin
      database: test-svc
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  port : 8083